[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "medplant-deepclassifier"
version = "0.1.0"
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "pandas",
    "scikit-learn",
    "opencv-python",
    "matplotlib",
    "pyyaml",
]