data:
  dataset_name: "indian-medicinal-leaves-dataset"
  dataset_url: "https://www.kaggle.com/datasets/aryashah2k/indian-medicinal-leaves-dataset"
  raw_dir: /home/kitne/University/2lvl/NS/medplant-deepclassifier/data/raw
  processed_dir: /home/kitne/University/2lvl/NS/medplant-deepclassifier/data/processed
  train_split: 0.5
  seed: 95123

model:
  input_size: [224, 224, 3]
  num_classes: 10  # Will be overridden by actual dataset class count
  feature_dim: 1024

training:
  batch_size: 16
  epochs: 10
  learning_rate: 1e-3
  optimizer: "sgdm"  # Options: "adam" or "sgdm"
  weight_decay: 0 #1e-5
  dropout_rate: 0.2
  cross_validation_folds: 10

bco:
  population_size: 100
  max_iterations: 1
  threshold: 0.5